version: '2.0'
services:
  postgres:
    image: postgres
    restart: always
    container_name: discord
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: discord
      POSTGRES_USER: discord
      POSTGRES_PASSWORD: discord
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  postgres:
